export const incrementDecrementOptions = {
  INCREMENT_N: 'INCREMENT_N',
  INCREMENT_M: 'INCREMENT_M',
  DECREMENT_N: 'DECREMENT_N',
  DECREMENT_M: 'DECREMENT_M',
  INCREMENT_CURRENT_MOVE: 'INCREMENT_CURRENT_MOVE',
  DECREMENT_CURRENT_MOVE: 'DECREMENT_CURRENT_MOVE',
}
